import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const directory = dirname(fileURLToPath(import.meta.url));
const root = resolve(directory, "..");
const args = process.argv.slice(2);
const check = args.includes("--check");
let network = args.includes("--local") ? "local" : args.find(arg => arg.startsWith("--network="))?.slice(10);
if (check && !network) network = readFileSync(resolve(directory, "subgraph.yaml"), "utf8").match(/^    network: ([a-z0-9-]+)$/m)?.[1];
if (!network || !/^[a-z][a-z0-9-]*$/.test(network)) throw new Error("Pass --local for local checks, or --network=<verified-provider-testnet-slug>; never guess a hosted network");
const manifest = JSON.parse(readFileSync(resolve(root, "registry/deployment.testnet.json"), "utf8"));
if (manifest.schemaVersion !== 1 || manifest.evmChainId !== 998 || manifest.network !== "testnet" ||
    !/^0x[0-9a-f]{40}$/.test(manifest.parlayVault) || !/^[1-9]\d*$/.test(manifest.parlayDeployBlock)) throw new Error("Invalid deployment manifest");
const abi = JSON.parse(readFileSync(resolve(root, "writer/abi/ParlayVault.json"), "utf8"))
  .filter(item => item.type === "event" && ["ParlayMinted", "ParlayResolved", "Transfer"].includes(item.name));
if (abi.length !== 3) throw new Error("Missing position events in ABI");
const outputs = {
  "abi/ParlayVault.json": JSON.stringify(abi, null, 2) + "\n",
  "src/deployment.ts": `// Generated from registry/deployment.testnet.json.\nexport const CHAIN_ID = "${manifest.evmChainId}";\nexport const VAULT = "${manifest.parlayVault}";\nexport const START_BLOCK = "${manifest.parlayDeployBlock}";\n`,
  "subgraph.yaml": `# Generated by generate.mjs. Network "local" is for tests, never hosted deployment.\nspecVersion: 1.0.0\nschema:\n  file: ./schema.graphql\ndataSources:\n  - kind: ethereum/contract\n    name: ParlayVault\n    network: ${network}\n    source:\n      address: "${manifest.parlayVault}"\n      abi: ParlayVault\n      startBlock: ${manifest.parlayDeployBlock}\n    mapping:\n      kind: ethereum/events\n      apiVersion: 0.0.9\n      language: wasm/assemblyscript\n      entities:\n        - Deployment\n        - Ticket\n        - WalletTicket\n      abis:\n        - name: ParlayVault\n          file: ./abi/ParlayVault.json\n      eventHandlers:\n        - event: ParlayMinted(indexed uint256,indexed address,bytes32,uint96,uint96)\n          handler: handleMint\n        - event: ParlayResolved(indexed uint256,uint8)\n          handler: handleResolve\n        - event: Transfer(indexed address,indexed address,indexed uint256)\n          handler: handleTransfer\n      file: ./src/mapping.ts\n`,
};
for (const [name, contents] of Object.entries(outputs)) {
  const file = resolve(directory, name);
  if (check) {
    if (readFileSync(file, "utf8") !== contents) throw new Error(`Generated subgraph drift: ${name}`);
  } else { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, contents); }
}
console.log(`PASS: subgraph manifest/ABI ${check ? "match" : "generated from"} v1 deployment (${network})`);
