// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {BaseTest} from "../BaseTest.sol";
import {CoreConstants} from "../../src/CoreConstants.sol";

/// ANCHOR TESTS — the oracle for the harness task graph (spec §6).
/// Workers make these green. DO NOT EDIT THIS FILE.
contract AnchorTest is BaseTest {
    /// DoD 1: deposit emits a byte-exact SplitOutcome payload.
    function test_DepositEmitsExactSplitPayload() public {
        vm.prank(user);
        vault.deposit(100e6);
        bytes memory expected = abi.encodePacked(
            uint8(1), uint24(17), abi.encode(uint8(0), uint32(QUESTION), uint32(OUTCOME), uint64(100e6 * MULT))
        );
        assertEq(writer.lastPayload(), expected, "split payload mismatch");
    }

    /// DoD 2: after Core processes the split, claim mints exactly N of each side.
    function test_ClaimAfterProcessMintsPair() public {
        depositAndClaim(100e6);
        assertEq(vault.oYes().balanceOf(user), 100e6);
        assertEq(vault.oNo().balanceOf(user), 100e6);
        assertEq(vault.oYes().totalSupply(), vault.oNo().totalSupply());
        assertEq(quote.balanceOf(user), 900e6);
    }

    /// DoD 3: no optimistic minting before Core has processed the split.
    function test_ClaimBeforeProcessReverts() public {
        vm.prank(user);
        vault.deposit(100e6);
        vm.expectRevert();
        vault.claimDeposit();
        assertEq(vault.oYes().totalSupply(), 0);
    }

    /// DoD 4: if Core silently drops the split, cancel + withdraw makes the
    /// depositor whole and mints nothing.
    function test_CancelAfterSilentDropRefunds() public {
        vm.prank(user);
        vault.deposit(100e6);
        sim.processTransfersOnly(); // transfer credited, split dropped
        sim.dropPendingActions();
        vm.warp(block.timestamp + vault.CANCEL_TIMEOUT() + 1);
        vm.prank(user);
        vault.cancelDeposit();
        sim.processAll(); // refund spotSend lands
        vm.prank(user);
        vault.withdraw();
        assertEq(quote.balanceOf(user), 1_000e6, "user not made whole");
        assertEq(vault.oYes().totalSupply(), 0);
        assertEq(vault.oNo().totalSupply(), 0);
    }

    /// DoD 5: oYES/oNO are transferable ERC-20s; only the vault mints/burns.
    function test_TokensTransferableAndVaultGated() public {
        depositAndClaim(100e6);
        vm.prank(user);
        vault.oYes().transfer(other, 40e6);
        assertEq(vault.oYes().balanceOf(other), 40e6);
        assertEq(vault.oYes().balanceOf(user), 60e6);

        vm.prank(other);
        vm.expectRevert();
        vault.oYes().mint(other, 1);
        vm.prank(other);
        vm.expectRevert();
        vault.oNo().burn(user, 1);
    }

    /// DoD 6: burning a full pair round-trips back to exactly N quote.
    function test_PairRedeemRoundTrip() public {
        depositAndClaim(100e6);
        vm.prank(user);
        vault.requestRedeem(100e6);
        assertEq(vault.oYes().totalSupply(), 0, "pair not burned on request");
        sim.processAll(); // merge executes on Core
        vault.claimRedeem();
        sim.processAll(); // spotSend lands on EVM side
        vm.prank(user);
        vault.withdraw();
        assertEq(quote.balanceOf(user), 1_000e6, "round trip lost funds");
    }

    /// DoD 7: settled redemption pays fraction / complement, backing never exceeded.
    function test_SettledRedemptionPaysFractions() public {
        depositAndClaim(100e6);
        vault.settle(0.75e18);
        sim.creditSettlement();
        vault.pullSettledFunds();
        sim.processAll();

        vm.prank(user);
        vault.redeemSettled(true, 100e6);
        assertEq(quote.balanceOf(user), 900e6 + 75e6, "yes side payout wrong");
        vm.prank(user);
        vault.redeemSettled(false, 100e6);
        assertEq(quote.balanceOf(user), 1_000e6, "no side payout wrong");
    }

    /// DoD 8: settle is one-shot and keeper-only.
    function test_SettleOnceKeeperOnly() public {
        vm.prank(other);
        vm.expectRevert();
        vault.settle(1e18);

        vault.settle(1e18); // keeper == address(this)
        vm.expectRevert();
        vault.settle(0);
    }

    /// DoD 9: no fund paths outside the redemption rules. Guard test — parts
    /// of it pass against stubs; it bites once functions are implemented.
    function test_NoStrayFundPaths() public {
        vm.prank(user);
        vm.expectRevert();
        vault.redeemSettled(true, 1); // not settled yet

        vm.expectRevert();
        vault.claimRedeem(); // nothing pending

        vm.prank(user);
        vm.expectRevert();
        vault.requestRedeem(1); // no tokens to burn
    }
}
